                                            %The index of the resonance
N=10;                                            %The order of submatrices
I=1;
l=1;                                            %Thickness of the slab                                        %The starting h
mode=0;                                         %0 imples even mode while 1 imples odd mode
mu_ratio=1;
eps_ratio=25/9;
R=0.6*(1:10);
h=(1./R)*0.1;


% k1=real(Outm1(1));
% k=k1*0.6;
% m=1;
% L11=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=2;
% L21=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=3;
% L31=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=4;
% L41=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=5;
% L51=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=6;
% L61=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=7;
% L71=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=8;
% L81=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=9;
% L91=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=10;
% L101=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% 
% 
% k1=real(Outm2(1));
% k=k1*0.6;
% m=1;
% L12=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=2;
% L22=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=3;
% L32=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=4;
% L42=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=5;
% L52=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=6;
% L62=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=7;
% L72=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=8;
% L82=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=9;
% L92=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=10;
% L102=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);


% k1=real(Outm3(1));
% k=k1*0.6;
% m=1;
% L13=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=2;
% L23=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=3;
% L33=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=4;
% L43=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=5;
% L53=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=6;
% L63=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=7;
% L73=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=8;
% L83=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=9;
% L93=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=10;
% L103=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);


% k1=(real(Outm4(1))+real(Outm5(1)))/2;
% k=k1*0.6;
% m=1;
% L14=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=2;
% L24=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=3;
% L34=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=4;
% L44=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=5;
% L54=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=6;
% L64=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=7;
% L74=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=8;
% L84=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=9;
% L94=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=10;
% L104=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% 
% 
% k1=(real(Outm5(1))+real(Outm6(1)))/2;
% k=k1*0.6;
% m=1;
% L15=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=2;
% L25=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=3;
% L35=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=4;
% L45=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=5;
% L55=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=6;
% L65=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=7;
% L75=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=8;
% L85=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=9;
% L95=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=10;
% L105=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);


% k1=(real(Outm6(1))+real(Outm7(1)))/2;
% k=k1*0.6;
% m=1;
% L16=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=2;
% L26=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=3;
% L36=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=4;
% L46=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=5;
% L56=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=6;
% L66=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=7;
% L76=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=8;
% L86=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=9;
% L96=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=10;
% L106=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);


% k1=(real(Outm7(1))+real(Outm8(1)))/2;
% k=k1*0.6;
% m=1;
% L17=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=2;
% L27=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=3;
% L37=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=4;
% L47=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=5;
% L57=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=6;
% L67=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=7;
% L77=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=8;
% L87=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=9;
% L97=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=10;
% L107=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);


% k1=(real(Outm8(1))+real(Outm9(1)))/2;
% k=k1*0.6;
% m=1;
% L18=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=2;
% L28=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=3;
% L38=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=4;
% L48=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=5;
% L58=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=6;
% L68=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=7;
% L78=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=8;
% L88=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=9;
% L98=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=10;
% L108=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);


k1=(real(Outm9(1))+real(Outm10(1)))/2;
k=k1*0.6;
% m=1;
% L19=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=2;
% L29=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=3;
% L39=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=4;
% L49=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=5;
% L59=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=6;
% L69=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=7;
% L79=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=8;
% L89=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
m=9;
L99=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
m=10;
L109=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);

% 
% k1=real(Outm10(1)+0.0015);
% k=k1*0.6;
% m=1;
% L110=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=2;
% L210=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=3;
% L310=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=4;
% L410=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=5;
% L510=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=6;
% L610=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=7;
% L710=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=8;
% L810=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=9;
% L910=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
% m=10;
% L1010=LinearSystemN(m,N,I,l,k,k1,mu_ratio,R(m),h(m),mode);
